version: '3'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    restart: always
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./NodeMicroservice/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  
  node-app:
    container_name: node-app
    restart: always
    build: .
    network_mode: host
    ports:
      - 3000:3000